### ISSUE TITLE
RSEM issue

### ISSUE THREAD

**Issue by RoseString** [YosefLab/BRAPeS#3]
Dear BRAPeS developers,

I was trying to run BRAPeS on the example data but had no success. RSEM was installed with bioconda, and the version is 1.3.2. 

The error message was "RSEM did not produce any transcript alignment files for heavy chain, please check the -rsem parameter." The output "BCR.out.BCRs.txt" only contains the header line, unlike the "example.output.BCRs.txt" file provided by you. The same error occurred when using the bioconda version 1.2.28-0 or a 1.3.2 version installed by our Linux administrator not using conda. 

The command is:
`brapes.py -genome mm10_ncbi -rsem ~/data/bin/anaconda3/envs/py27/bin/ -path Example/proc_data/ -sumF Example/BRAPeS_out/BCR.out -output BRAPeS_out/BCR.out -score 15 -top 10 -byExp -unmapped unmapped.bam -bam sorted.bam`

The full log is:
> 2019-12-04 16:47:23.910158 Working on: ERR1467921
> 2019-12-04 16:47:23.918773 Pre-processing heavy chain
> 2019-12-04 16:47:23.927829 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 139 unmapped reads to the reads file
> 2019-12-04 16:47:27.259014 Pre-processing kappa chain
> Added 957 unmapped reads to the reads file
> 2019-12-04 16:47:30.819533 Pre-processing lambda chain
> 2019-12-04 16:47:30.826005 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 222 unmapped reads to the reads file
> 2019-12-04 16:47:34.052156 Reconstructing heavy chains
> 2019-12-04 16:47:37.536691 Reconstructing kappa chains
> 2019-12-04 16:57:23.322620 Reconstructing lambda chains
> 2019-12-04 16:57:23.327186 Creating full BCR sequences
> 2019-12-04 16:57:23.418055 Running RSEM to quantify expression of all possible isotypes
> sorting bam file
> sorting bam file
> 2019-12-04 16:57:25.624145 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-04 16:57:25.634136 Finding productive CDR3
> 2019-12-04 16:57:25.916152 Performing CDR1 and CDR2 reconstruction
> 
> Loading reads...
> 
> Working on IGHV9-2...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-2. Skipping...
> 
> Working on IGHV9-3...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-3. Skipping...
> 
> 
> Loading reads...
> 
> Working on IGKV1-122...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-122. Skipping...
> 
> Working on IGKV1-110...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-110. Skipping...
> 
> Working on IGKV1-117...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-117. Skipping...
> 
> RSEM did not produce any transcript alignment files for heavy chain, please check the -rsem parameter
> RSEM did not produce any transcript alignment files for kappa chain, please check the -rsem parameter
> 2019-12-04 16:57:26.427233 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-04 16:57:26.427649 Writing results to summary file

When I did not specify the "-rsem" argument (RSEM was already added to the PATH), another error occurred:

> 2019-12-04 17:05:44.695056 Working on: ERR1467921
> 2019-12-04 17:05:44.703218 Pre-processing heavy chain
> 2019-12-04 17:05:44.712471 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 139 unmapped reads to the reads file
> 2019-12-04 17:05:47.875784 Pre-processing kappa chain
> Added 957 unmapped reads to the reads file
> 2019-12-04 17:05:51.229238 Pre-processing lambda chain
> 2019-12-04 17:05:51.235855 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 222 unmapped reads to the reads file
> 2019-12-04 17:05:54.209072 Reconstructing heavy chains
> 2019-12-04 17:05:57.320026 Reconstructing kappa chains
> 2019-12-04 17:15:28.427234 Reconstructing lambda chains
> 2019-12-04 17:15:28.432419 Creating full BCR sequences
> 2019-12-04 17:15:28.523025 Running RSEM to quantify expression of all possible isotypes
> Traceback (most recent call last):
>   File "/home/dsun3/bin/BRAPeS/brapes.py", line 2157, in <module>
>     args.Fr)
>   File "/home/dsun3/bin/BRAPeS/brapes.py", line 52, in runBCRpipe
>     hvr_path, genome)
>   File "/home/dsun3/bin/BRAPeS/brapes.py", line 321, in runSingleCell
>     runRsem(outDir, rsem, bowtie2, fullTcrFileHeavy, fullTcrFileKappa,fullTcrFileLambda, output, samtools, False)
>   File "/home/dsun3/bin/BRAPeS/brapes.py", line 1185, in runRsem
>     runRSEMonOneFile(fullTcrFileHeavy, rsem, bowtie2, rsemIndDir, output, samtools, "heavy", secondRound)
>   File "/home/dsun3/bin/BRAPeS/brapes.py", line 1216, in runRSEMonOneFile
>     '-q', resF, rsemIndDir + '/VDJ.' + chain + '.seq'], stdout=devnull, stderr=devnull)
>   File "/home/dsun3/data/bin/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 172, in call
>     return Popen(*popenargs, **kwargs).wait()
>   File "/home/dsun3/data/bin/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/home/dsun3/data/bin/anaconda3/envs/py27/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

Any ideas what might be going wrong? Thank you!

**Comment by shakea02** [comment]
Hello,

Thank you for your interest in BRAPeS. 
Regarding the second issue (when RSEM is added to the PATH), there was a bug in the program and it's now fixed, thank you for noticing! 
As for the first issue, I downloaded the newest RSEM version and ran BRAPeS on the example data and it worked without any problem. Based on the output log you posted, I think you might be running an older version of BRAPeS, can you pull the new version and try again?

Thanks,
Shaked

**Comment by RoseString** [comment]
Thank you for the quick reply. I downloaded the latest github version. Without '-rsem', the second issue is now fixed. However, the first error persisted. I tried on a different computer but still got the same error message ('RSEM did not produce any transcript alignment files for heavy chain, please check the -rsem parameter'). 

Is there anything else that you think might be causing the issue? Thanks again!

```
python brapes.py -genome mm10_ncbi -path Example/proc_data/ -sumF Example/BRAPeS_out/BCR.out -output BRAPeS_out/BCR.out -score 15 -top 10 -byExp -unmapped unmapped.bam -bam sorted.bam
```

> 2019-12-04 22:02:53.932638 Working on: ERR1467921
> 2019-12-04 22:02:54.441392 Pre-processing heavy chain
> 2019-12-04 22:02:54.482511 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 139 unmapped reads to the reads file
> 2019-12-04 22:03:00.373301 Pre-processing kappa chain
> Added 957 unmapped reads to the reads file
> 2019-12-04 22:03:06.693289 Pre-processing lambda chain
> 2019-12-04 22:03:06.705354 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 222 unmapped reads to the reads file
> 2019-12-04 22:03:12.336326 Reconstructing heavy chains
> 2019-12-04 22:03:17.032362 Reconstructing kappa chains
> 2019-12-04 22:17:23.496863 Reconstructing lambda chains
> 2019-12-04 22:17:23.503861 Creating full BCR sequences
> 2019-12-04 22:17:23.656102 Running RSEM to quantify expression of all possible isotypes
> sorting bam file
> sorting bam file
> 2019-12-04 22:17:29.067154 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-04 22:17:29.080890 Finding productive CDR3
> 2019-12-04 22:17:29.954443 Performing CDR1 and CDR2 reconstruction
> 
> Loading reads...
> 
> Working on IGHV9-2...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-2. Skipping...
> 
> Working on IGHV9-3...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-3. Skipping...
> 
> 
> Loading reads...
> 
> Working on IGKV1-122...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-122. Skipping...
> 
> Working on IGKV1-110...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-110. Skipping...
> 
> Working on IGKV1-117...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-117. Skipping...
> 
> RSEM did not produce any transcript alignment files for heavy chain, please check the -rsem parameter
> RSEM did not produce any transcript alignment files for kappa chain, please check the -rsem parameter
> 2019-12-04 22:17:31.212076 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-04 22:17:31.213223 Writing results to summary file

**Comment by shakea02** [comment]
Hello,

The log output you sent is not of the latest version, since the somatic hypermutation correction was changed and the output it provides now is different. If you go to the github page and go to the HVR_rec folder, do you see the latest version (from 7/25)? I'm attaching below the log output of the newest version.

However, this might not be the issue. Can you try running these two command lines from the terminal and see if you get any error?

path-to-rsem/rsem-prepare-reference --bowtie2 path-to-BRAPeS/Example/proc_data/ERR1467921/BRAPeS_out/test.rsem.ver.heavy.full.BCRs.fa VDJ.test.seq

path-to-rsem/rsem-calculate-expression --no-qualities --bowtie2 --bowtie2-mismatch-rate 0.0 --paired-end path-to-BRAPeS/Example/proc_data/ERR1467921/BRAPeS_out/test.rsem.ver.heavy.R1.fa path-to-BRAPeS/Example/proc_data/ERR1467921/BRAPeS_out/test.rsem.ver.heavy.R2.fa  VDJ.test.seq VDJ.test.rsem.out


Here's the log output that I'm getting from BRAPeS:

2019-12-05 11:26:02.702965 Working on: ERR1467921
2019-12-05 11:26:02.731251 Pre-processing heavy chain
2019-12-05 11:26:02.758475 Did not find any V-J reads, searching for V-C and J-C reads:
Added 139 unmapped reads to the reads file
2019-12-05 11:26:08.922235 Pre-processing kappa chain
Added 957 unmapped reads to the reads file
2019-12-05 11:26:15.217287 Pre-processing lambda chain
2019-12-05 11:26:15.240906 Did not find any V-J reads, searching for V-C and J-C reads:
Added 222 unmapped reads to the reads file
2019-12-05 11:26:21.955844 Reconstructing heavy chains
2019-12-05 11:26:25.591583 Reconstructing kappa chains
2019-12-05 11:36:12.712462 Reconstructing lambda chains
2019-12-05 11:36:12.718622 Creating full BCR sequences
2019-12-05 11:36:12.973163 Running RSEM to quantify expression of all possible isotypes
sorting bam file
sorting bam file
2019-12-05 11:36:19.225158 Did not reconstruct any lambda chains, not running RSEM on this chain
2019-12-05 11:36:19.260914 Finding productive CDR3
2019-12-05 11:36:19.717973 Performing CDR1 and CDR2 reconstruction

Loading reads...

Working on IGHV9-2...

Reconstructing CDR1
Reconstruction Succeeded!
Reconstructing CDR2
Reconstruction Succeeded!
Reconstructing FR1
Reconstruction Succeeded!
Reconstructing FR2
Reconstruction Succeeded!
Reconstructing FR3
Reconstruction Succeeded!
Reconstructing FR4
Reconstruction Succeeded!

Working on IGHV9-3...

Reconstructing CDR1
Reconstruction Succeeded!
Reconstructing CDR2
Reconstruction Succeeded!
Reconstructing FR1
Reconstruction Succeeded!
Reconstructing FR2
Reconstruction Succeeded!
Reconstructing FR3
Reconstruction Succeeded!
Reconstructing FR4
Reconstruction Succeeded!


Loading reads...

Working on IGKV1-122...

Reconstructing CDR1
Reconstruction Succeeded!
Reconstructing CDR2
Reconstruction Succeeded!
Reconstructing FR1
Reconstruction Succeeded!
Reconstructing FR2
Reconstruction Succeeded!
Reconstructing FR3
Reconstruction Succeeded!
Reconstructing FR4
Reconstruction Succeeded!

Working on IGKV1-117...

Reconstructing CDR1
Reconstruction Succeeded!
Reconstructing CDR2
Reconstruction Succeeded!
Reconstructing FR1
Reconstruction Succeeded!
Reconstructing FR2
Reconstruction Succeeded!
Reconstructing FR3
Reconstruction Succeeded!
Reconstructing FR4
Reconstruction Succeeded!

Working on IGKV1-110...

Reconstructing CDR1
Reconstruction Succeeded!
Reconstructing CDR2
Reconstruction Succeeded!
Reconstructing FR1
Reconstruction Succeeded!
Reconstructing FR2
Reconstruction Succeeded!
Reconstructing FR3
Reconstruction Succeeded!
Reconstructing FR4
Reconstruction Succeeded!

sorting bam file
sorting bam file
2019-12-05 11:54:46.614080 Did not reconstruct any lambda chains, not running RSEM on this chain
2019-12-05 11:54:47.083402 Writing results to summary file

**Comment by RoseString** [comment]
Thank you @shakea02 . I did the installation with 'git clone https://github.com/YosefLab/BRAPeS.git' last night, so I'm not sure why it's not the latest version. Should I do it another way?

Regarding the two commands, both finished without errors. However, when changing slightly your python code to output RSEM standard out and standard error,  an error occurred in the RSEM reference preparation step, where the program complained "Number of transcripts in the reference is less than 1!". I checked the "BCR.out.heavy.full.BCRs.bestIso.CDR1.CDR2.reconstructions.fasta.BCRs.fasta" file and it is empty. 


The full log is:

> 2019-12-05 14:45:04.515627 Working on: ERR1467921
> 2019-12-05 14:45:04.524096 Pre-processing heavy chain
> 2019-12-05 14:45:04.534343 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 139 unmapped reads to the reads file
> 2019-12-05 14:45:07.971786 Pre-processing kappa chain
> Added 957 unmapped reads to the reads file
> 2019-12-05 14:45:11.679573 Pre-processing lambda chain
> 2019-12-05 14:45:11.686279 Did not find any V-J reads, searching for V-C and J-C reads:
> Added 222 unmapped reads to the reads file
> 2019-12-05 14:45:15.019389 Reconstructing heavy chains
> 2019-12-05 14:45:18.549340 Reconstructing kappa chains
> 2019-12-05 14:54:54.171313 Reconstructing lambda chains
> 2019-12-05 14:54:54.177234 Creating full BCR sequences
> 2019-12-05 14:54:54.268029 Running RSEM to quantify expression of all possible isotypes
> rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.full.BCRs.fa
> 
> rsem-preref Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq.transcripts.fa 1 Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq -q
> 
> bowtie2-build -f -q Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq.idx.fa Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq
> Building a SMALL index
> 
> bowtie2 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R2.fa | samtools view -S -b -o Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out.bam -
> 
> rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.stat/BCR.out.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out.bam 2 -tag XM -q
> 
> rsem-build-read-index 32 0 1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out_alignable_1.fa Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out_alignable_2.fa
> 
> rsem-run-em Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.heavy.seq 2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.stat/BCR.out.heavy.rsem.out -p 1 -b Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp/BCR.out.heavy.rsem.out.bam 0 -q
> Warning: Read ERR1467921.638508 is ignored due to at least one of the mates' length < seed length (= 25)!
> Warning: Read ERR1467921.109703 is ignored due to at least one of the mates' length < seed length (= 25)!
> Warning: There are 2 reads ignored in total.
> Time Used for EM.cpp : 0 h 00 m 00 s
> 
> rm -rf Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.rsem.out.temp
> 
> rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.full.BCRs.fa
> 
> rsem-preref Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq.transcripts.fa 1 Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq -q
> 
> bowtie2-build -f -q Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq.idx.fa Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq
> Building a SMALL index
> 
> bowtie2 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R2.fa | samtools view -S -b -o Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out.bam -
> 
> rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.stat/BCR.out.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out.bam 2 -tag XM -q
> 
> rsem-build-read-index 32 0 1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out_alignable_1.fa Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out_alignable_2.fa
> 
> rsem-run-em Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind5925621/VDJ.kappa.seq 2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.stat/BCR.out.kappa.rsem.out -p 1 -b Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp/BCR.out.kappa.rsem.out.bam 0 -q
> Warning: Read ERR1467921.82207 is ignored due to at least one of the mates' length < seed length (= 25)!
> Warning: There are 1 reads ignored in total.
> Time Used for EM.cpp : 0 h 00 m 00 s
> 
> rm -rf Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.rsem.out.temp
> 
> 2019-12-05 14:54:56.562326 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-05 14:54:56.567939 Finding productive CDR3
> 2019-12-05 14:54:56.852498 Performing CDR1 and CDR2 reconstruction
> 
> Loading reads...
> 
> Working on IGHV9-2...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-2. Skipping...
> 
> Working on IGHV9-3...
> 
> No IMGT reference for IGHJ4. Will skip FR4 reconstruction...
> No IMGT reference for IGHV9-3. Skipping...
> 
> 
> Loading reads...
> 
> Working on IGKV1-122...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-122. Skipping...
> 
> Working on IGKV1-110...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-110. Skipping...
> 
> Working on IGKV1-117...
> 
> No IMGT reference for IGKJ1. Will skip FR4 reconstruction...
> No IMGT reference for IGKV1-117. Skipping...
> 
> rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.full.BCRs.bestIso.CDR1.CDR2.reconstructions.fasta.BCRs.fasta
> Number of transcripts in the reference is less than 1!
> "rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.full.BCRs.bestIso.CDR1.CDR2.reconstructions.fasta.BCRs.fasta" failed! Plase check if you provide correct parameters/options for the pipeline!
> bowtie2 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R2.fa | samtools view -S -b -o Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.temp/BCR.out.afterCDRrec.heavy.rsem.out.bam -
> Could not locate a Bowtie index corresponding to basename "Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq"
> Error: Encountered internal Bowtie 2 exception (#1)
> Command: /home/dsun3/data/bin/anaconda3/envs/py27/bin/bowtie2-align-s --wrapper basic-0 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.heavy.R2.fa
> (ERR): bowtie2-align exited with value 1
> 
> rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.temp/BCR.out.afterCDRrec.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.stat/BCR.out.afterCDRrec.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.temp/BCR.out.afterCDRrec.heavy.rsem.out.bam 2 -tag XM -q
> Cannot open Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq.grp! It may not exist.
> "rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.heavy.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.temp/BCR.out.afterCDRrec.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.stat/BCR.out.afterCDRrec.heavy.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.heavy.rsem.out.temp/BCR.out.afterCDRrec.heavy.rsem.out.bam 2 -tag XM -q" failed! Plase check if you provide correct parameters/options for the pipeline!
> rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.full.BCRs.bestIso.CDR1.CDR2.reconstructions.fasta.BCRs.fasta
> Number of transcripts in the reference is less than 1!
> "rsem-synthesis-reference-transcripts Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq 1 0 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.full.BCRs.bestIso.CDR1.CDR2.reconstructions.fasta.BCRs.fasta" failed! Plase check if you provide correct parameters/options for the pipeline!
> bowtie2 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R2.fa | samtools view -S -b -o Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.temp/BCR.out.afterCDRrec.kappa.rsem.out.bam -
> Could not locate a Bowtie index corresponding to basename "Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq"
> Error: Encountered internal Bowtie 2 exception (#1)
> Command: /home/dsun3/data/bin/anaconda3/envs/py27/bin/bowtie2-align-s --wrapper basic-0 -f --sensitive --dpad 0 --gbar 99999999 --mp 1,1 --np 1 --score-min L,0,-0.0 -I 1 -X 1000 --no-mixed --no-discordant -p 1 -k 200 --quiet -x Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq -1 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R1.fa -2 Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.kappa.R2.fa
> (ERR): bowtie2-align exited with value 1
> 
> rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.temp/BCR.out.afterCDRrec.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.stat/BCR.out.afterCDRrec.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.temp/BCR.out.afterCDRrec.kappa.rsem.out.bam 2 -tag XM -q
> Cannot open Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq.grp! It may not exist.
> "rsem-parse-alignments Example/proc_data/ERR1467921/BRAPeS_out/rsem_ind54981819/VDJ.kappa.seq Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.temp/BCR.out.afterCDRrec.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.stat/BCR.out.afterCDRrec.kappa.rsem.out Example/proc_data/ERR1467921/BRAPeS_out/BCR.out.afterCDRrec.kappa.rsem.out.temp/BCR.out.afterCDRrec.kappa.rsem.out.bam 2 -tag XM -q" failed! Plase check if you provide correct parameters/options for the pipeline!
> RSEM did not produce any transcript alignment files for heavy chain, please check the -rsem parameter
> RSEM did not produce any transcript alignment files for kappa chain, please check the -rsem parameter
> 2019-12-05 14:54:57.414421 Did not reconstruct any lambda chains, not running RSEM on this chain
> 2019-12-05 14:54:57.414748 Writing results to summary file

**Comment by shakea02** [comment]
Ok, now I understand the problem better, thanks! 
The RSEM crash is because the somatic hypermutation correction isn't working properly and doesn't produce any reconstruction. I believe it's the same problem that causes you to get the different output log but I'm not sure what is causing it. @gabe-raulet do you have any suggestions as to why when cloning the git we get the older CDR1/2 reconstruction version?

**Comment by RoseString** [comment]
The program can now run successfully with the updated version.
